# GitHub Sponsors funding file
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: jaz-on
ko_fi: jasonrouet
