# WordPress + MariaDB optimized for Coolify
# Improved stability, security and performance
# Repository: https://github.com/jaz-on/wp-coolify
services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
      - './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
      - './wp-rest-fix.php:/var/www/html/wp-content/mu-plugins/wp-rest-fix.php'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_DEBUG', false);
    depends_on:
      - mariadb
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1/wp-admin/install.php'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  mariadb:
    image: 'mariadb:lts'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
  wordpress-cli:
    image: 'wordpress:cli'
    user: '33'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - wordpress
      - mariadb
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    entrypoint: ['tail', '-f', '/dev/null']
volumes:
  wordpress-files:
  mariadb-data:
networks:
  default:
    name: $COOLIFY_NETWORK_NAME
    external: true
